# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DesafioListaDeEventos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DesafioListaDeEventos
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'Alamofire'
    pod 'RxAlamofire'
    pod 'RxDataSources', '~> 3.0'
    pod 'RxBlocking'

  target 'DesafioListaDeEventosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DesafioListaDeEventosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
